### ISSUE TITLE
update profile picture

### ISSUE THREAD

**Issue by 18O4** [cosrnic/cosrnic#1]
issue: profile picture has not been updated to the latest one.
below i attached the pfp im talking about
![kindahotwoman.png](https://user-images.githubusercontent.com/64557095/180663527-13dd07e0-da5c-4033-9a40-17a6b752d008.png)

**Comment by AlbieGames** [comment]
Thats very major you must fix this.

**Comment by cosrnic** [comment]
I will not be updating as it is a temporary profile picture, also please fuck off.
